# run: conda env create --file environment.yml

name: apienv
dependencies:
- python==3.8
- pandas==1.5.3
- pip
- pip:
  # works for regular pip packages
  - requests==2.28.1
  - jupyter
  - scikit-learn
  - folium
  - torch==1.13.1 torchvision==0.14.1 -f https://download.pytorch.org/whl/torch_stable.html
  - autogluon
